[package]
name = "wave_function_sudoku"
version = "0.1.0"
edition = "2021"
authors = ["Ardu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"
egui = "0.21"
egui-macroquad = "0.15"

